export const DRAWER_ACTION = "DRAWER";
export const PRODUCT_DATA_ACTION = "GET_PRODUCT_DATA";
export const PRODUCT_INFO_ACTION = "GET_INFO";
export const ADD_BASKET_ACTION = "ADD_BASKET";
export const REMOVE_BASKET_ACTION = "REMOVE_BASKET";
export const SEARCH_ACTION = "SEARCH";
